CREATE DATABASE IF NOT EXISTS shmasstest CHARACTER SET utf8mb4;
USE shmasstest;

CREATE TABLE users (
 id INT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(255) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL,
 name VARCHAR(100) NOT NULL,
 phone VARCHAR(20),
 role ENUM('admin','manager','user') DEFAULT 'user',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
